services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: passw0rd725
      POSTGRES_DB: pocdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_tool
    ports:
      - "9081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: no-reply@gmail.com
      PGADMIN_DEFAULT_PASSWORD: passw0rd725
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
